const AT = {
  // Projects
  PROJECTS_READ_REQUEST: "PROJECTS_READ_REQUEST",
  PROJECTS_READ_SUCCESS: "PROJECTS_READ_SUCCESS",
  PROJECTS_READ_FAILURE: "PROJECTS_READ_FAILURE",
  PROJECT_CREATE_REQUEST: "PROJECT_CREATE_REQUEST",
  PROJECT_REMOVE_REQUEST: "PROJECT_REMOVE_REQUEST",
  // Teams
  TEAMS_READ_REQUEST: "TEAMS_READ_REQUEST",
  TEAMS_READ_SUCCESS: "TEAMS_READ_SUCCESS",
  TEAMS_READ_FAILURE: "TEAMS_READ_FAILURE",
  TEAM_CREATE_REQUEST: "TEAM_CREATE_REQUEST",
  TEAM_REMOVE_REQUEST: "TEAM_REMOVE_REQUEST",
  TEAM_READ_REQUEST: "TEAM_READ_REQUEST",
  TEAM_READ_SUCCESS: "TEAM_READ_SUCCESS",
  TEAM_READ_FAILURE: "TEAM_READ_FAILURE",
  // Users
  USERS_READ_REQUEST: "USERS_READ_REQUEST",
  USERS_READ_SUCCESS: "USERS_READ_SUCCESS",
  USERS_READ_FAILURE: "USERS_READ_FAILURE",
  USER_READ_REQUEST: "USER_READ_REQUEST",
  USER_READ_SUCCESS: "USER_READ_SUCCESS",
  USER_READ_FAILURE: "USER_READ_FAILURE",
  USER_CREATE_REQUEST: "USER_CREATE_REQUEST",
  USER_REMOVE_REQUEST: "USER_REMOVE_REQUEST",
  //Profile
  PROFILES_READ_REQUEST: "PROFILE_READ_REQUEST",
  PROFILES_READ_SUCCESS: "PROFILE_READ_SUCCESS",
  PROFILES_READ_FAILURE: "PROFILE_READ_FAILURE",
  PROFILE_CREATE_REQUEST: "PROFILE_CREATE_REQUEST",
  PROFILE_REMOVE_REQUEST: "PROFILE_REMOVE_REQUEST",
  PROFILE_READ_REQUEST: "PROFILE_READ_REQUEST",
  PROFILE_READ_SUCCESS: "PROFILE_READ_SUCCESS",
  PROFILE_READ_FAILURE: "PROFILE_READ_FAILURE"
};

export default AT;
