const AT = {
  // Projects
  PROJECT_CREATE_REQUEST: "PROJECT_CREATE_REQUEST",
  PROJECT_REMOVE_REQUEST: "PROJECT_REMOVE_REQUEST",
  // Teams
  TEAM_CREATE_REQUEST: "TEAM_CREATE_REQUEST",
  TEAM_REMOVE_REQUEST: "TEAM_REMOVE_REQUEST"
};

export default AT;
