const AT = {
  // Projects
  PROJECTS_READ_REQUEST: "PROJECTS_READ_REQUEST",
  PROJECTS_READ_SUCCESS: "PROJECTS_READ_SUCCESS",
  PROJECTS_READ_FAILURE: "PROJECTS_READ_FAILURE",
  PROJECT_CREATE_REQUEST: "PROJECT_CREATE_REQUEST",
  PROJECT_REMOVE_REQUEST: "PROJECT_REMOVE_REQUEST",
  // Teams
  TEAMS_READ_REQUEST: "TEAMS_READ_REQUEST",
  TEAMS_READ_SUCCESS: "TEAMS_READ_SUCCESS",
  TEAMS_READ_FAILURE: "TEAMS_READ_FAILURE",
  TEAM_CREATE_REQUEST: "TEAM_CREATE_REQUEST",
  TEAM_REMOVE_REQUEST: "TEAM_REMOVE_REQUEST",
  // Users
  USERS_READ_REQUEST: "USERS_READ_REQUEST",
  USERS_READ_SUCCESS: "USERS_READ_SUCCESS",
  USERS_READ_FAILURE: "USERS_READ_FAILURE",
  USER_CREATE_REQUEST: "USER_CREATE_REQUEST",
  USER_REMOVE_REQUEST: "USER_REMOVE_REQUEST"
};

export default AT;
